### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by OfficialLilKev** [BajanVlogs/ObbyBlaster#1]
Add dispenser support

**Comment by QuiverlyRivalry** [comment]
fake dev

**Comment by HBIDamian** [comment]
How about fix it so that the tnt always goes in the direction of the button. 
![image](https://user-images.githubusercontent.com/10010369/33516640-137c3b38-d76e-11e7-97ee-0341e7f349d8.png)

At the moment it is not the left direction of the button instead of forward. 
![image](https://user-images.githubusercontent.com/10010369/33516661-6beb8a4e-d76e-11e7-9714-b2d2c7a9bb7c.png)

Until then, I am reverting it to a draft, as the plugin does work, it's just not working quite there...


***


Also, please refrain from editing people's messages, as it is really untrustworthy to do so. 

***

Many thanks, 

TheDeibo
Poggit Reviewer
